AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ComparisonOperator:
    Type: String
    
  DimensionName:
    Type: String
    
  EvaluationPeriods:
    Type: Number
  
  Instance1:
    Type: String
    
  Instance2:
    Type: String
    
  MetricName:
    Type: String
    
  Namespace:
    Type: String
    
  Period:
    Type: Number
    
  Prefix:
    Type: String
    
  Statistic:
    Type: String
    
  Threshold:
    Type: Number
    
  Topic2:
    Type: String
    

Resources:
  Alarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref Topic2
      AlarmName: !Sub "${Prefix}-alarm-01"
      ComparisonOperator: !Ref ComparisonOperator
      Dimensions:
        - Name: !Ref DimensionName
          Value: !Ref Instance1
      EvaluationPeriods: !Ref EvaluationPeriods
      MetricName: !Ref MetricName
      Namespace: !Ref Namespace
      Period: !Ref Period
      Statistic: !Ref Statistic
      Threshold: !Ref Threshold
      
  Alarm2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref Topic2
      AlarmName: !Sub "${Prefix}-alarm-02"
      ComparisonOperator: !Ref ComparisonOperator
      Dimensions:
        - Name: !Ref DimensionName
          Value: !Ref Instance2
      EvaluationPeriods: !Ref EvaluationPeriods
      MetricName: !Ref MetricName
      Namespace: !Ref Namespace
      Period: !Ref Period
      Statistic: !Ref Statistic
      Threshold: !Ref Threshold
