AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: udemy-001
    
  ACMCertificate:
    Type: String
    #Default:
    
  ALBHostedZoneId:
    Type: String
    Default: Z14GRHDCWA56QT
    
  CloudWatchAlarmComparisonOperator:
    Type: String
    Default: GreaterThanThreshold
    
  CloudWatchAlarmDimensionName:
    Type: String
    Default: InstanceId
    
  CloudWatchAlarmEvaluationPeriods:
    Type: Number
    Default: 1
    
  CloudWatchAlarmMetricName:
    Type: String
    Default: CPUUtilization
    
  CloudWatchAlarmNamespace:
    Type: String
    Default: AWS/EC2
    
  CloudWatchAlarmPeriod:
    Type: Number
    Default: 60
    
  CloudWatchAlarmStatistic:
    Type: String
    Default: Average
    
  CloudWatchAlarmThreshold:
    Type: Number
    Default: 0
    
  CloudFrontCacheTTL:
    Type: Number
    Default: 0

  DBAllocatedStorage:
    Type: Number
    Default: 20
    
  DBEngine:
    Type: String
    Default: mysql
    
  DBEngineVersion:
    Type: String
    Default: 8.0.28
    
  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    
  DBMasterUsername:
    Type: String
    Default: testuser
    
  DBMasterUserPassword:
    Type: String
    Default: Passw0rd
    
  DBName:
    Type: String
    Default: wordpress
    
  DistributionHostedZoneId:
    Type: String
    Default: Z2FDTNDATAQYW2
    
  DomainHostedZoneId:
    Type: String
    Default: [domain-hosted-zone-id]
    
  DomainName:
    Type: String
    Default: [domain-name]
    
  EventBusName:
    Type: String
    Default: default
    
  HTTPPort:
    Type: Number
    Default: 80

  ImageBuilderParentImage:
    Type: String
    Default: arn:aws:imagebuilder:ap-northeast-1:aws:image/amazon-linux-2-arm64/x.x.x
  
  ImageBuilderPlatform:
    Type: String
    Default: Linux
    
  ImageBuilderSupportedOsVersion:
    Type: String
    Default: Amazon Linux 2
    
  ImageBuilderVersion:
    Type: String
    Default: 1.0.0
    
  InstanceImageId:
    Type: String
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2
    
  InstanceType:
    Type: String
    Default: t4g.micro
    
  LambdaArchitecture:
    Type: String
    Default: arm64
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler
    
  LambdaRuntime:
    Type: String
    Default: python3.8
    
  MySQLPort:
    Type: Number
    Default: 3306
    
  Route53TTL:
    Type: Number
    Default: 300
      
  WaitConditionTimeout:
    Type: Number
    Default: 3600
    
  WordPressAdminEmail:
    Type: String
    Default: [email-address]
    
  WordPressAdminPassword:
    Type: String
    Default: Passw0rd
    
  WordPressAdminUser:
    Type: String
    Default: admin
    
  WordPressTitle:
    Type: String
    Default: awstut !
      
    
Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3.yaml"
      Parameters:
        Prefix: !Ref Prefix
        
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ALBStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudfront.yaml"
      Parameters:
        BucketName: !GetAtt S3Stack.Outputs.BucketName
        BucketRegionalDomainName: !GetAtt S3Stack.Outputs.BucketRegionalDomainName
        CacheTTL: !Ref CloudFrontCacheTTL
        Certificate: !Ref ACMCertificate
        DomainName: !Ref DomainName
        Prefix: !Ref Prefix
  
  LambdaStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-01.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        
  LambdaStack2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-02.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        EventBusName: !Ref EventBusName
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        
  SNSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack1
      - LambdaStack2
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-sns.yaml"
      Parameters:
        Function1: !GetAtt LambdaStack1.Outputs.Function1
        Function2: !GetAtt LambdaStack2.Outputs.Function2
        FunctionArn1: !GetAtt LambdaStack1.Outputs.FunctionArn1
        FunctionArn2: !GetAtt LambdaStack2.Outputs.FunctionArn2
        MailAddress: !Ref WordPressAdminEmail
        Prefix: !Ref Prefix
        
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-vpc.yaml"
      Parameters:
        AvailabilityZone1: a
        AvailabilityZone2: d
        CidrIp1: 10.0.1.0/24
        CidrIp2: 10.0.2.0/24
        CidrIp3: 10.0.3.0/24
        CidrIp4: 10.0.4.0/24
        HTTPPort: !Ref HTTPPort
        MySQLPort: !Ref MySQLPort
        Prefix: !Ref Prefix
        VPCCidrBlock: 10.0.0.0/16
        
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-rds.yaml"
      Parameters:
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBEngine: !Ref DBEngine
        DBEngineVersion: !Ref DBEngineVersion
        DBInstanceClass: !Ref DBInstanceClass
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBName: !Ref DBName
        DBSecurityGroup: !GetAtt VPCStack.Outputs.DBSecurityGroup
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        Prefix: !Ref Prefix
        
  ImageBuilderStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SNSStack
      - RDSStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-imagebuilder.yaml"
      Parameters:
        BucketName: !GetAtt S3Stack.Outputs.BucketName
        DBInstanceEndpointAddress: !GetAtt RDSStack.Outputs.DBInstanceEndpointAddress
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBName: !Ref DBName
        DomainName: !Ref DomainName
        ImageBuilderParentImage: !Ref ImageBuilderParentImage
        ImageBuilderPlatform: !Ref ImageBuilderPlatform
        ImageBuilderSupportedOsVersion: !Ref ImageBuilderSupportedOsVersion
        ImageBuilderVersion: !Ref ImageBuilderVersion
        InstanceSecurityGroup: !GetAtt VPCStack.Outputs.InstanceSecurityGroup
        InstanceType: !Ref InstanceType
        Prefix: !Ref Prefix
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        Topic1: !GetAtt SNSStack.Outputs.Topic1
        WordPressAdminEmail: !Ref WordPressAdminEmail
        WordPressAdminPassword: !Ref WordPressAdminPassword
        WordPressAdminUser: !Ref WordPressAdminUser
        WordPressTitle: !Ref WordPressTitle
        
  LambdaStack3:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ImageBuilderStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-03.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        ImagePipelineArn: !GetAtt ImageBuilderStack.Outputs.ImagePipelineArn
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        
  LambdaStack4:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ImageBuilderStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-04.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        EventBusName: !Ref EventBusName
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        WaitConditionTimeout: !Ref WaitConditionTimeout
        
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack4
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-ec2.yaml"
      Parameters:
        InstanceSecurityGroup: !GetAtt VPCStack.Outputs.InstanceSecurityGroup
        InstanceType: !Ref InstanceType
        ParameterAmi: !GetAtt LambdaStack1.Outputs.ParameterAmi
        Prefix: !Ref Prefix
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
          
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-alb.yaml"
      Parameters:
        ALBSecurityGroup: !GetAtt VPCStack.Outputs.ALBSecurityGroup
        HTTPPort: !Ref HTTPPort
        Instance1: !GetAtt EC2Stack.Outputs.Instance1
        Instance2: !GetAtt EC2Stack.Outputs.Instance2
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        Prefix: !Ref Prefix
        VPC: !GetAtt VPCStack.Outputs.VPC
        
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 2
        HealthCheckTimeoutSeconds: 5
        HealthCheckIntervalSeconds: 30
        HttpCode: 200
        
  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack
      - SNSStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudwatch.yaml"
      Parameters:
        ComparisonOperator: !Ref CloudWatchAlarmComparisonOperator
        DimensionName: !Ref CloudWatchAlarmDimensionName
        EvaluationPeriods: !Ref CloudWatchAlarmEvaluationPeriods
        Instance1: !GetAtt EC2Stack.Outputs.Instance1
        Instance2: !GetAtt EC2Stack.Outputs.Instance2
        MetricName: !Ref CloudWatchAlarmMetricName
        Namespace: !Ref CloudWatchAlarmNamespace
        Period: !Ref CloudWatchAlarmPeriod
        Prefix: !Ref Prefix
        Statistic: !Ref CloudWatchAlarmStatistic
        Threshold: !Ref CloudWatchAlarmThreshold
        Topic2: !GetAtt SNSStack.Outputs.Topic2

  Route53Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CloudFrontStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-route53.yaml"
      Parameters:
        ALBDNSName: !GetAtt ALBStack.Outputs.ALBDNSName
        ALBHostedZoneId: !Ref ALBHostedZoneId
        DistributionDomainName: !GetAtt CloudFrontStack.Outputs.DistributionDomainName
        DistributionHostedZoneId: !Ref DistributionHostedZoneId
        DomainHostedZoneId: !Ref DomainHostedZoneId
        DomainName: !Ref DomainName
        TTL: !Ref Route53TTL
