AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ALBDNSName:
    Type: String
    
  ALBHostedZoneId:
    Type: String
  
  DistributionDomainName:
    Type: String
    
  DistributionHostedZoneId:
    Type: String
    
  DomainHostedZoneId:
    Type: String
    
  DomainName:
    Type: String

  TTL:
    Type: Number
    

Resources:
  DnsRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget: 
        DNSName: !Ref ALBDNSName
        HostedZoneId: !Ref ALBHostedZoneId
      HostedZoneId: !Ref DomainHostedZoneId
      Name: !Ref DomainName
      Type: A
        
  DnsRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DomainHostedZoneId
      Name: !Sub "static.${DomainName}"
      ResourceRecords:
        - !Ref DistributionDomainName
      TTL: !Ref TTL
      Type: CNAME
