AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Type: String
    
  BucketRegionalDomainName:
    Type: String
    
  CacheTTL:
    Type: Number
    
  Certificate:
    Type: String
  
  DomainName:
    Type: String

  Prefix:
    Type: String
    

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "static.${DomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: !Ref BucketName
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: !Ref CacheTTL
          MaxTTL: !Ref CacheTTL
          MinTTL: !Ref CacheTTL
        Enabled: true
        Origins:
          - DomainName: !Ref BucketRegionalDomainName
            Id: !Ref BucketName
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        
        
Outputs:
  Distribution:
    Value: !Ref Distribution

  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
