AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Type: String
    
  Distribution:
    Type: String


Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          Action:
            - s3:GetObject
          Effect: Allow
          Principal: "*"
          Resource: !Sub "arn:aws:s3:::${BucketName}/*"
