AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Type: String

  #DBInstanceEndpointAddress:
  #  Type: String
  #  
  #DBMasterUsername:
  #  Type: String
  #  
  #DBMasterUserPassword:
  #  Type: String
  #  
  #DBName:
  #  Type: String
  
  #ImageId:
  #  Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    
  InstanceSecurityGroup:
    Type: String

  InstanceType:
    Type: String
    
  ParameterAmi:
    Type: String
    
  Prefix:
    Type: String
    
  #PrivateSubnet1:
  #  Type: String
    
  #PrivateSubnet2:
  #  Type: String
  
  PublicSubnet1:
    Type: String
    
  PublicSubnet2:
    Type: String
    
  #UserData:
  #  Type: String
    

Resources:
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Sub "{{resolve:ssm:${ParameterAmi}}}"
      #ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref PublicSubnet1
      #UserData: !Base64 |
      #UserData:
      #  Fn::Base64:
      #    !Sub |
      #      #!/bin/bash -xe
      #      yum update -y
      #      yum install -y httpd
      #      
      #      amazon-linux-extras enable -y php7.4
      #      yum install -y php php-gd php-mysqlnd php-xmlrpc -y
      #      
      #      yum install -y mariadb
      #      
      #      #wget https://wordpress.org/latest.tar.gz
      #      #tar -xzf latest.tar.gz
      #      #cp wordpress/wp-config-sample.php wordpress/wp-config.php
      #      #
      #      #sed -i -e 's/database_name_here/${DBName}/' ./wordpress/wp-config.php 
      #      #sed -i -e 's/username_here/${DBMasterUsername}/' ./wordpress/wp-config.php 
      #      #sed -i -e 's/password_here/${DBMasterUserPassword}/' ./wordpress/wp-config.php 
      #      #sed -i -e 's/localhost/${DBInstanceEndpointAddress}/' ./wordpress/wp-config.php
      #      #
      #      #cp -r wordpress/* /var/www/html/
      #      #chown -R apache /var/www
      #      #chgrp -R apache /var/www
      #      #chmod 2775 /var/www
      #      #find /var/www -type d -exec sudo chmod 2775 {} \;
      #      #find /var/www -type f -exec sudo chmod 0644 {} \;
      #      
      #      systemctl start httpd
      #      systemctl enable httpd
      
  #EIP:
  #  Type: AWS::EC2::EIP
  #  Properties:
  #    Domain: vpc
  #    
  #EIPAssociation:
  #  Type: AWS::EC2::EIPAssociation
  #  Properties:
  #    AllocationId: !GetAtt EIP.AllocationId
  #    InstanceId: !Ref Instance1
        
  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Sub "{{resolve:ssm:${ParameterAmi}}}"
      #ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref PublicSubnet2
            
  #Instance2:
  #  Type: AWS::EC2::Instance
  #  Properties:
  #    #IamInstanceProfile: !Ref InstanceProfile
  #    ImageId: !Ref ImageId
  #    InstanceType: !Ref InstanceType
  #    NetworkInterfaces:
  #      - DeviceIndex: 0
  #        SubnetId: !Ref PrivateSubnet2
  #        GroupSet:
  #          - !Ref InstanceSecurityGroup
  #    UserData: !Ref UserData
      
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
  
  InstanceRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
                #- ssm.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: S3Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}/*"
              - Effect: Allow
                Action:
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketOwnershipControls
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
        
      
Outputs:
  Instance1:
    Value: !Ref Instance1
      
  Instance2:
    Value: !Ref Instance2